"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc
import trucking_pb2

class PositionDataStreamerStub:
    """option py_generic_services = true;"""

    def __init__(self, channel: grpc.Channel) -> None: ...
    getPositionData: grpc.UnaryUnaryMultiCallable[
        trucking_pb2.TimeDelta,
        trucking_pb2.PositionDataStream,
    ]

class PositionDataStreamerServicer(metaclass=abc.ABCMeta):
    """option py_generic_services = true;"""

    @abc.abstractmethod
    def getPositionData(
        self,
        request: trucking_pb2.TimeDelta,
        context: grpc.ServicerContext,
    ) -> trucking_pb2.PositionDataStream: ...

def add_PositionDataStreamerServicer_to_server(servicer: PositionDataStreamerServicer, server: grpc.Server) -> None: ...

class ConfigurationStreamerStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    startFromConfig: grpc.UnaryUnaryMultiCallable[
        trucking_pb2.ConfigAsString,
        trucking_pb2.Void,
    ]

class ConfigurationStreamerServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def startFromConfig(
        self,
        request: trucking_pb2.ConfigAsString,
        context: grpc.ServicerContext,
    ) -> trucking_pb2.Void: ...

def add_ConfigurationStreamerServicer_to_server(servicer: ConfigurationStreamerServicer, server: grpc.Server) -> None: ...
