"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class TimeDelta(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SECONDS_FIELD_NUMBER: builtins.int
    seconds: builtins.float
    def __init__(
        self,
        *,
        seconds: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["seconds", b"seconds"]) -> None: ...

global___TimeDelta = TimeDelta

@typing_extensions.final
class PositionDataStream(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRUCKS_FIELD_NUMBER: builtins.int
    @property
    def trucks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___TruckPositionsAtTime]: ...
    def __init__(
        self,
        *,
        trucks: collections.abc.Iterable[global___TruckPositionsAtTime] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["trucks", b"trucks"]) -> None: ...

global___PositionDataStream = PositionDataStream

@typing_extensions.final
class TruckPositionsAtTime(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRUCKS_FIELD_NUMBER: builtins.int
    TIME_FIELD_NUMBER: builtins.int
    @property
    def trucks(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Truck]: ...
    time: builtins.float
    def __init__(
        self,
        *,
        trucks: collections.abc.Iterable[global___Truck] | None = ...,
        time: builtins.float = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["time", b"time", "trucks", b"trucks"]) -> None: ...

global___TruckPositionsAtTime = TruckPositionsAtTime

@typing_extensions.final
class Truck(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRUCK_ID_FIELD_NUMBER: builtins.int
    DESTINATION_ID_FIELD_NUMBER: builtins.int
    CURR_SPEED_FIELD_NUMBER: builtins.int
    CURR_ACCEL_FIELD_NUMBER: builtins.int
    ROAD_ID_FIELD_NUMBER: builtins.int
    PROGRESS_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    truck_id: builtins.int
    destination_id: builtins.int
    curr_speed: builtins.float
    curr_accel: builtins.float
    road_id: builtins.int
    progress: builtins.float
    @property
    def path(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PathElement]: ...
    def __init__(
        self,
        *,
        truck_id: builtins.int = ...,
        destination_id: builtins.int = ...,
        curr_speed: builtins.float = ...,
        curr_accel: builtins.float = ...,
        road_id: builtins.int = ...,
        progress: builtins.float = ...,
        path: collections.abc.Iterable[global___PathElement] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["curr_accel", b"curr_accel", "curr_speed", b"curr_speed", "destination_id", b"destination_id", "path", b"path", "progress", b"progress", "road_id", b"road_id", "truck_id", b"truck_id"]) -> None: ...

global___Truck = Truck

@typing_extensions.final
class PathElement(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: builtins.int
    ROAD_ID_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    road_id: builtins.int
    def __init__(
        self,
        *,
        node_id: builtins.int = ...,
        road_id: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["NodeOrRoad", b"NodeOrRoad", "node_id", b"node_id", "road_id", b"road_id"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["NodeOrRoad", b"NodeOrRoad", "node_id", b"node_id", "road_id", b"road_id"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["NodeOrRoad", b"NodeOrRoad"]) -> typing_extensions.Literal["node_id", "road_id"] | None: ...

global___PathElement = PathElement
