name: BackendTest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: BackendTest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install -r backend/requirements.txt
    - name: mypy
      run: |
        mypy backend/
    - name: unit-tests
      run: |
        cd backend
        python3 test/test_env.py
        python3 test/test_graph.py
